### ISSUE TITLE
非常好的脚本，但有两个问题

### ISSUE THREAD

**Issue by hongshui3000** [smrtos/Zephyr2VSC#1]
1. 生成 settings.json文件会完全替换原来的文件，而不是只替换或追加"files.exclude"， "C_Cpp.exclusionPolicy"等这些项目
2. files.exclude屏蔽的文件无法在vscode 下面显示，会影响一些内容的重构编辑。比如，刚开始编译了hello world sample 现在又想编辑另一个例子目录，这个时候只能修改settings.json，这样比较麻烦。https://github.com/microsoft/vscode-cpptools/issues/8895

**Comment by smrtos** [comment]
多谢，有空我会看一下，谢谢反馈。
Thanks for the feedback!
